version: '3'
services:
  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: kitabisa
      MYSQL_DATABASE: testing
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - "database:/var/lib/mysql"
    ports:
      - "3306:3306"
volumes:
  database: